global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using ScratchMAUI.Pages;
global using CommunityToolkit.Mvvm.ComponentModel;
global using ScratchMAUI.ViewModel;
global using ScratchMAUI.Models;
global using CommunityToolkit.Mvvm.Input;